# Generated by Django 5.2b1 on 2025-10-12 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorClave',
            fields=[
                ('id_actor_clave', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Actor Clave')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('puesto', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PESTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Político'), ('EC', 'Económico'), ('S', 'Social'), ('T', 'Tecnológico'), ('EO', 'Ecológico'), ('L', 'Legal')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sistema')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id_subsistema', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Subsistema')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencia', models.IntegerField()),
                ('actor_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_fuente', to='haapar_unla_app.actorclave')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema')),
            ],
        ),
        migrations.AddField(
            model_name='actorclave',
            name='subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tema')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('horizonte', models.CharField(max_length=50)),
                ('territorio', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sistema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tema'),
        ),
        migrations.CreateModel(
            name='TendenciaExterna',
            fields=[
                ('id_tendencia_externa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tendencia Externa')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorTendencia',
            fields=[
                ('id_indicador_tendencia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Indicador')),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('formula', models.TextField()),
                ('tendencia_externa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tendenciaexterna')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id_variable', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Variable')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('I', 'Interna'), ('E', 'Externa')], max_length=1)),
                ('pestels', models.ManyToManyField(to='haapar_unla_app.pestel')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema')),
            ],
        ),
        migrations.CreateModel(
            name='Influencia',
            fields=[
                ('id_influencia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Influencia')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variable_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencias_destino', to='haapar_unla_app.variable')),
                ('variable_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencias_origen', to='haapar_unla_app.variable')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorVariable',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Indicador')),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('formula', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.variable')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Evaluacion')),
                ('importancia', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Importancia')),
                ('incertidumbre', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Incertidumbre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('ELIMINADO', 'Eliminado'), ('MODIFICADO', 'Modificado')], default='CREADO', max_length=20)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_mod', to=settings.AUTH_USER_MODEL)),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haapar_unla_app.variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariableTendencia',
            fields=[
                ('id_variable_tendencia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Variable-Tendencia')),
                ('impacto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tendenciaexterna')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.variable')),
            ],
        ),
    ]
