# Generated by Django 5.2.4 on 2025-09-04 16:29

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorClave',
            fields=[
                ('id_actor_clave', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Actor Clave')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('puesto', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PESTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Político'), ('EC', 'Económico'), ('S', 'Social'), ('T', 'Tecnológico'), ('EO', 'Ecológico'), ('L', 'Legal')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Sistema')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('grupo_id', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'haapar_unla_app_usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subsistema',
            fields=[
                ('id_subsistema', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Subsistema')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencia', models.IntegerField()),
                ('actor_clave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_fuente', to='haapar_unla_app.actorclave')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema')),
            ],
        ),
        migrations.AddField(
            model_name='actorclave',
            name='subsistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tema')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('horizonte', models.CharField(max_length=50)),
                ('territorio', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sistema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tema'),
        ),
        migrations.CreateModel(
            name='TendenciaExterna',
            fields=[
                ('id_tendencia_externa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Tendencia Externa')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorTendencia',
            fields=[
                ('id_indicador_tendencia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Indicador')),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('formula', models.TextField()),
                ('tendencia_externa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tendenciaexterna')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id_variable', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Variable')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('I', 'Interna'), ('E', 'Externa')], max_length=1)),
                ('pestels', models.ManyToManyField(to='haapar_unla_app.pestel')),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema')),
            ],
        ),
        migrations.CreateModel(
            name='Influencia',
            fields=[
                ('id_influencia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Influencia')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variable_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencias_destino', to='haapar_unla_app.variable')),
                ('variable_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencias_origen', to='haapar_unla_app.variable')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorVariable',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Indicador')),
                ('nombre_corto', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('formula', models.TextField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.variable')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Evaluacion')),
                ('importancia', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Importancia')),
                ('incertidumbre', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Incertidumbre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_creador', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modificador', to=settings.AUTH_USER_MODEL)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.variable')),
            ],
        ),
        migrations.CreateModel(
            name='VariableTendencia',
            fields=[
                ('id_variable_tendencia', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Variable-Tendencia')),
                ('impacto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tendencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tendenciaexterna')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.variable')),
            ],
        ),
    ]
