# Generated by Django 5.1.6 on 2025-08-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadortendencia',
            old_name='id_indicador_tendendencia',
            new_name='id_indicador_tendencia',
        ),
        migrations.RenameField(
            model_name='indicadortendencia',
            old_name='tendenciaExterna',
            new_name='tendencia_externa',
        ),
        migrations.RenameField(
            model_name='relacionactor',
            old_name='id_actor_clave',
            new_name='actor_clave',
        ),
        migrations.RenameField(
            model_name='relacionactor',
            old_name='id_subsistema',
            new_name='subsistema',
        ),
        migrations.RenameField(
            model_name='subsistema',
            old_name='id_sistema',
            new_name='sistema',
        ),
        migrations.RenameField(
            model_name='tendenciaexterna',
            old_name='id_tendenciaExterna',
            new_name='id_tendencia_externa',
        ),
        migrations.RenameField(
            model_name='tendenciaexterna',
            old_name='subsitema',
            new_name='subsistema',
        ),
        migrations.RenameField(
            model_name='variabletendencia',
            old_name='id_variableTendencia',
            new_name='id_variable_tendencia',
        ),
        migrations.AlterField(
            model_name='pestel',
            name='tipo',
            field=models.CharField(choices=[('P', 'Político'), ('EC', 'Económico'), ('S', 'Social'), ('T', 'Tecnológico'), ('EO', 'Ecológico'), ('L', 'Legal')], max_length=2),
        ),
        migrations.AlterField(
            model_name='variable',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
