# Generated by Django 5.1.6 on 2025-08-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0002_rename_id_indicador_tendendencia_indicadortendencia_id_indicador_tendencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorclave',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subsistema',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tema',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tendenciaexterna',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variable',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
