# Generated by Django 5.2.11 on 2026-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0002_evaluaciontendencia_evaluacionvariable_historial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='importancia',
            field=models.IntegerField(blank=True, choices=[(0, '0 - Nada crítico'), (1, '1 - Poco crítico'), (2, '2 - Crítico'), (3, '3 - Muy crítico')], null=True),
        ),
        migrations.AddField(
            model_name='historial',
            name='incertidumbre',
            field=models.IntegerField(blank=True, choices=[(0, '0 - Nada incierto'), (1, '1 - Poco incierto'), (2, '2 - Incierto'), (3, '3 - Muy incierto')], null=True),
        ),
    ]
