# Generated by Django 5.2.13 on 2026-04-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0003_historial_importancia_historial_incertidumbre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='importancia',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='incertidumbre',
        ),
    ]
