# Generated by Django 5.2.3 on 2025-09-20 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0003_actorclave_activo_subsistema_activo_tema_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionactor',
            name='actor_clave',
        ),
        migrations.AlterField(
            model_name='relacionactor',
            name='influencia',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('puesto', models.CharField(max_length=100)),
                ('emite', models.BooleanField(default=False)),
                ('recibe', models.BooleanField(default=False)),
                ('influencia', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2)),
                ('activo', models.BooleanField(default=True)),
                ('subsistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.subsistema')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tema')),
            ],
        ),
        migrations.AddField(
            model_name='relacionactor',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.actor'),
            preserve_default=False,
        ),
    ]
