# Generated by Django 5.1.6 on 2025-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0003_actorclave_activo_subsistema_activo_tema_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('ELIMINADO', 'Eliminado'), ('MODIFICADO', 'Modificado')], default='CREADO', max_length=20),
        ),
    ]
