# Generated by Django 5.1.6 on 2025-09-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0004_evaluacion_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haapar_unla_app.variable'),
        ),
    ]
