# Generated by Django 5.1.7 on 2025-09-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0004_remove_relacionactor_actor_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendenciaexterna',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tendencias_externas', to='haapar_unla_app.tema'),
            preserve_default=False,
        ),
    ]
