# Generated by Django 5.2.13 on 2026-04-23 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0004_remove_historial_importancia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='temas_colaborando', to=settings.AUTH_USER_MODEL),
        ),
    ]
