# Generated by Django 5.2.4 on 2025-10-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0005_alter_evaluacion_variable'),
        ('haapar_unla_app', '0005_tendenciaexterna_tema'),
    ]

    operations = [
    ]
