# Generated by Django 5.1.7 on 2026-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0005_tema_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
