# Generated by Django 5.1.7 on 2026-05-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0006_historial_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendenciaexterna',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tema'),
        ),
    ]
