# Generated by Django 5.1.7 on 2026-05-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0007_tendenciaexterna_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendenciaexterna',
            name='tema',
        ),
    ]
