# Generated by Django 5.2.14 on 2026-05-23 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0008_remove_tendenciaexterna_tema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IAInteraction',
            fields=[
                ('id_interaccion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Interacción IA')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='haapar_unla_app.tema')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
