# Generated by Django 5.1.6 on 2026-05-24 23:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haapar_unla_app', '0009_iainteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evaluacionvariable',
            index=models.Index(fields=['variable', 'usuario'], name='haapar_unla_variabl_2c81a2_idx'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['variable'], name='haapar_unla_variabl_dd9c73_idx'),
        ),
        migrations.AddIndex(
            model_name='historial',
            index=models.Index(fields=['fecha'], name='haapar_unla_fecha_9c0b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='influencia',
            index=models.Index(fields=['variable_origen', 'variable_destino'], name='haapar_unla_variabl_04ce53_idx'),
        ),
    ]
