# Generated by Django 5.1.6 on 2026-08-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "haapar_unla_app",
            "0010_evaluacionvariable_haapar_unla_variabl_2c81a2_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS unaccent;"),
    ]
