# Generated by Django 5.1.6 on 2026-09-06 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haapar_unla_app", "0011_auto_20260731_2320"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscenarioSchwartz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuadrante", models.CharField(max_length=50)),
                ("nombre_marketinero", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                (
                    "subsistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escenarios",
                        to="haapar_unla_app.subsistema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfluenciaActor",
            fields=[
                (
                    "id_influencia",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Influencia Actor",
                    ),
                ),
                (
                    "valor",
                    models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)]),
                ),
                (
                    "actor_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencias_recibidas",
                        to="haapar_unla_app.actorclave",
                    ),
                ),
                (
                    "actor_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencias_ejercidas",
                        to="haapar_unla_app.actorclave",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actor_origen", "actor_destino"],
                        name="haapar_unla_actor_o_6dd33f_idx",
                    )
                ],
                "unique_together": {("actor_origen", "actor_destino")},
            },
        ),
    ]
